# Generated by Django 5.2.15 on 2026-08-08 15:26

import django.db.models.deletion
import plane.db.models.github_integration
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0122_alter_draftissue_assignees_alter_issue_assignees_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubProjectLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('repository_full_name', models.CharField(max_length=255, unique=True)),
                ('webhook_secret', models.CharField(default=plane.db.models.github_integration.generate_github_webhook_secret, max_length=255)),
                ('sync_issues', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Github Project Link',
                'verbose_name_plural': 'Github Project Links',
                'db_table': 'github_project_links',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='GithubPullRequestLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('repository_full_name', models.CharField(max_length=255)),
                ('pr_number', models.PositiveIntegerField()),
                ('pr_url', models.URLField(max_length=800)),
                ('title', models.TextField()),
                ('state', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('merged', 'Merged')], default='open', max_length=20)),
                ('is_draft', models.BooleanField(default=False)),
                ('checks_status', models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('success', 'Success'), ('failure', 'Failure')], default='none', max_length=20)),
                ('head_branch', models.CharField(blank=True, max_length=500)),
                ('head_sha', models.CharField(blank=True, db_index=True, max_length=64)),
                ('merged_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_pull_requests', to='db.issue')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Github Pull Request Link',
                'verbose_name_plural': 'Github Pull Request Links',
                'db_table': 'github_pull_request_links',
                'ordering': ('-created_at',),
                'unique_together': {('repository_full_name', 'pr_number')},
            },
        ),
    ]
