# Generated by Django 5.2.15 on 2026-08-08 18:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0123_githubprojectlink_githubpullrequestlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubpullrequestlink',
            name='reviewers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='GithubCommitLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('repository_full_name', models.CharField(max_length=255)),
                ('sha', models.CharField(db_index=True, max_length=40)),
                ('message', models.TextField()),
                ('url', models.URLField(max_length=800)),
                ('author_name', models.CharField(blank=True, max_length=255)),
                ('authored_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_commits', to='db.issue')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Github Commit Link',
                'verbose_name_plural': 'Github Commit Links',
                'db_table': 'github_commit_links',
                'ordering': ('-authored_at',),
                'unique_together': {('repository_full_name', 'sha', 'issue')},
            },
        ),
    ]
