# Generated by Django 5.2.15 on 2026-08-09 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0125_email_intake'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailintakeconfig',
            name='html_template',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='emailintakeconfig',
            name='signature_html',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='emailintakeconfig',
            name='state_on_agent_reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='db.state'),
        ),
        migrations.AddField(
            model_name='emailintakeconfig',
            name='state_on_customer_reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='db.state'),
        ),
    ]
