# Generated by Django 5.2.15 on 2026-08-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0126_email_intake_template_and_state_automation'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailintakeconfig',
            name='imap_folder',
            field=models.CharField(default='INBOX', max_length=255),
        ),
        migrations.AddField(
            model_name='githubprojectlink',
            name='last_webhook_received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
