# Generated by Django 5.2.15 on 2026-08-18 08:54

import django.db.models.deletion
import plane.db.models.webhook_intake
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0127_email_intake_folder'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookFeedbackLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('source', models.CharField(choices=[('USERBACK', 'Userback')], default='USERBACK', max_length=30)),
                ('external_feedback_id', models.CharField(max_length=255)),
                ('external_comment_ids', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('issue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_feedback_link', to='db.issue')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Webhook Feedback Link',
                'verbose_name_plural': 'Webhook Feedback Links',
                'db_table': 'webhook_feedback_links',
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('project', 'source', 'external_feedback_id'), name='unique_webhook_feedback_link_per_source')],
            },
        ),
        migrations.CreateModel(
            name='WebhookIntakeConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('source', models.CharField(choices=[('USERBACK', 'Userback')], default='USERBACK', max_length=30)),
                ('webhook_token', models.CharField(default=plane.db.models.webhook_intake._generate_webhook_token, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Webhook Intake Config',
                'verbose_name_plural': 'Webhook Intake Configs',
                'db_table': 'webhook_intake_configs',
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('project', 'source'), name='unique_webhook_intake_source_per_project')],
            },
        ),
    ]
